default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: matias
  password: sebastian10

development:
  <<: *default
  database: barber_saas_development
test:
  <<: *default
  database: barber_saas_test
production:
  <<: *default
  database: barber_saas_production
  username: barber_saas
  password: <%= ENV["BARBER_SAAS_DATABASE_PASSWORD"] %>
